name: spotify
description: Spotify analog project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_svg: ^1.1.4
  firebase_core: ^1.21.1
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/artist.png

    - assets/icons/history.svg
    - assets/icons/notifications.svg
    - assets/icons/settings.svg

  fonts:
    - family: GraphikBlack
      fonts:
        - asset: assets/fonts/GraphikBlack.otf

    - family: GraphikBlackItalic
      fonts:
        - asset: assets/fonts/GraphikBlackItalic.otf

    - family: GraphikBold
      fonts:
        - asset: assets/fonts/GraphikBold.otf

    - family: GraphikBoldItalic
      fonts:
        - asset: assets/fonts/GraphikBoldItalic.otf

    - family: GraphikExtralight
      fonts:
        - asset: assets/fonts/GraphikExtralight.otf

    - family: GraphikExtralightItalic
      fonts:
        - asset: assets/fonts/GraphikExtralightItalic.otf

    - family: GraphikLight
      fonts:
        - asset: assets/fonts/GraphikLight.otf

    - family: GraphikLightItalic
      fonts:
        - asset: assets/fonts/GraphikLightItalic.otf

    - family: GraphikMedium
      fonts:
        - asset: assets/fonts/GraphikMedium.otf

    - family: GraphikMediumItalic
      fonts:
        - asset: assets/fonts/GraphikMediumItalic.otf

    - family: GraphikRegular
      fonts:
        - asset: assets/fonts/GraphikRegular.otf

    - family: GraphikRegularItalic
      fonts:
        - asset: assets/fonts/GraphikRegularItalic.otf

    - family: GraphikSemibold
      fonts:
        - asset: assets/fonts/GraphikSemibold.otf

    - family: GraphikSemiboldItalic
      fonts:
        - asset: assets/fonts/GraphikSemiboldItalic.otf

    - family: GraphikSuper
      fonts:
        - asset: assets/fonts/GraphikSuper.otf

    - family: GraphikSuperItalic
      fonts:
        - asset: assets/fonts/GraphikSuperItalic.otf

    - family: GraphikThin
      fonts:
        - asset: assets/fonts/GraphikThin.otf

    - family: GraphikThinItalic
      fonts:
        - asset: assets/fonts/GraphikThinItalic.otf
